
package clientews.servicio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EncryptWS", targetNamespace = "http://servicio.en.com.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EncryptWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encrypt", targetNamespace = "http://servicio.en.com.it/", className = "clientews.servicio.Encrypt")
    @ResponseWrapper(localName = "encryptResponse", targetNamespace = "http://servicio.en.com.it/", className = "clientews.servicio.EncryptResponse")
    @Action(input = "http://servicio.en.com.it/EncryptWS/encryptRequest", output = "http://servicio.en.com.it/EncryptWS/encryptResponse")
    public String encrypt(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
