
package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EncryptWSImplService", targetNamespace = "http://servicio.en.com.it/", wsdlLocation = "http://localhost:8080/EncryptWSImplService/EncryptWSImpl?wsdl")
public class EncryptWSImplService
    extends Service
{

    private final static URL ENCRYPTWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENCRYPTWSIMPLSERVICE_EXCEPTION;
    private final static QName ENCRYPTWSIMPLSERVICE_QNAME = new QName("http://servicio.en.com.it/", "EncryptWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/EncryptWSImplService/EncryptWSImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENCRYPTWSIMPLSERVICE_WSDL_LOCATION = url;
        ENCRYPTWSIMPLSERVICE_EXCEPTION = e;
    }

    public EncryptWSImplService() {
        super(__getWsdlLocation(), ENCRYPTWSIMPLSERVICE_QNAME);
    }

    public EncryptWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENCRYPTWSIMPLSERVICE_QNAME, features);
    }

    public EncryptWSImplService(URL wsdlLocation) {
        super(wsdlLocation, ENCRYPTWSIMPLSERVICE_QNAME);
    }

    public EncryptWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENCRYPTWSIMPLSERVICE_QNAME, features);
    }

    public EncryptWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EncryptWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EncryptWS
     */
    @WebEndpoint(name = "EncryptWSImplPort")
    public EncryptWS getEncryptWSImplPort() {
        return super.getPort(new QName("http://servicio.en.com.it/", "EncryptWSImplPort"), EncryptWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EncryptWS
     */
    @WebEndpoint(name = "EncryptWSImplPort")
    public EncryptWS getEncryptWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.en.com.it/", "EncryptWSImplPort"), EncryptWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENCRYPTWSIMPLSERVICE_EXCEPTION!= null) {
            throw ENCRYPTWSIMPLSERVICE_EXCEPTION;
        }
        return ENCRYPTWSIMPLSERVICE_WSDL_LOCATION;
    }

}
