
package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EncriptacionImplService", targetNamespace = "http://beans/", wsdlLocation = "http://localhost:8080/EncriptacionImplService/EncriptacionImpl?wsdl")
public class EncriptacionImplService
    extends Service
{

    private final static URL ENCRIPTACIONIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENCRIPTACIONIMPLSERVICE_EXCEPTION;
    private final static QName ENCRIPTACIONIMPLSERVICE_QNAME = new QName("http://beans/", "EncriptacionImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/EncriptacionImplService/EncriptacionImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENCRIPTACIONIMPLSERVICE_WSDL_LOCATION = url;
        ENCRIPTACIONIMPLSERVICE_EXCEPTION = e;
    }

    public EncriptacionImplService() {
        super(__getWsdlLocation(), ENCRIPTACIONIMPLSERVICE_QNAME);
    }

    public EncriptacionImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENCRIPTACIONIMPLSERVICE_QNAME, features);
    }

    public EncriptacionImplService(URL wsdlLocation) {
        super(wsdlLocation, ENCRIPTACIONIMPLSERVICE_QNAME);
    }

    public EncriptacionImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENCRIPTACIONIMPLSERVICE_QNAME, features);
    }

    public EncriptacionImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EncriptacionImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Encriptacion
     */
    @WebEndpoint(name = "EncriptacionImplPort")
    public Encriptacion getEncriptacionImplPort() {
        return super.getPort(new QName("http://beans/", "EncriptacionImplPort"), Encriptacion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Encriptacion
     */
    @WebEndpoint(name = "EncriptacionImplPort")
    public Encriptacion getEncriptacionImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://beans/", "EncriptacionImplPort"), Encriptacion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENCRIPTACIONIMPLSERVICE_EXCEPTION!= null) {
            throw ENCRIPTACIONIMPLSERVICE_EXCEPTION;
        }
        return ENCRIPTACIONIMPLSERVICE_WSDL_LOCATION;
    }

}
