/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.com.interfaces;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SingleSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import mx.com.domain.Cliente;
import mx.com.domain.Contacto;
import mx.com.domain.Contribuyente;
import mx.com.domain.Direccion;
import mx.com.domain.Empresa;
import mx.com.domain.Isr;
import mx.com.service.ClienteService;

/**
 *
 * @author guina
 */
public class ModificarForm extends javax.swing.JFrame {

    /**
     * Creates new form ModificarForm
     */
    public ModificarForm() {
        initComponents();
        this.idTexto.setEnabled(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Modificar Datos");
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        ClienteService servicio = new ClienteService();
        List<Cliente> clientes = servicio.listarClientes();
        isrValores.removeAllItems();
        this.isrValores.addItem("--------");
        contribuyenteValores.removeAllItems();
        contribuyenteValores.addItem("--------");
        for (Cliente c : clientes) {
            modelo.addRow(new Object[]{c.getIdCliente().toString(), c.getNombre(), c.getApellido(),
                c.getCui().toString(), c.getEdad(), c.getIdContacto().getTelefono1(),
                c.getIdContacto().getTelefono2(), c.getIdDireccion().getDireccion(),
                c.getNit(), c.getIdContacto().getEmail(), c.getIdContribuyente().getDescripcion(),
                c.getIdIsr().getTipoIsr(), c.getIdEmpresa().getNombreEmpresa()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idTexto = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        ApellidoTexto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NombreTexto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edadTexto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cuiTexto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telefono2Texto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        telefono1Texto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nitTexto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        direcctionTexto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        contribuyenteValores = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        emailTexto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        empresaTexto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        isrValores = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        nitFiled = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cuiField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cliente", "Nombre", "Apellido", "CUI", "Edad", "Telefono 1", "Telefono 2", "Direccion", "NIT", "Email", "Contribuyente", "ISR", "Empresa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(189, 6, 800, 195);

        jButton1.setText("Volver a Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(860, 410, 120, 32);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Actualizar");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(6, 21, 165, 42);

        jLabel1.setText("ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(6, 127, 40, 16);
        jPanel1.add(idTexto);
        idTexto.setBounds(6, 161, 74, 24);

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(ApellidoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, -1));

        jLabel3.setText("Apellido");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel2.add(NombreTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 74, -1));

        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        jPanel2.add(edadTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 74, -1));

        jLabel6.setText("Edad");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));
        jPanel2.add(cuiTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 74, -1));

        jLabel5.setText("CUI");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));
        jPanel2.add(telefono2Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 74, -1));

        jLabel8.setText("Telefono 2");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));
        jPanel2.add(telefono1Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 74, -1));

        jLabel7.setText("Telefono 1");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));
        jPanel2.add(nitTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 74, -1));

        jLabel10.setText("Nit");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));
        jPanel2.add(direcctionTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 74, -1));

        jLabel9.setText("Direccion");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        contribuyenteValores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(contribuyenteValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 90, -1));

        jLabel12.setText("Contribuyente");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));
        jPanel2.add(emailTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 74, -1));

        jLabel11.setText("Email");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));
        jPanel2.add(empresaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 74, -1));

        jLabel14.setText("Empresa");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        isrValores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        isrValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isrValoresActionPerformed(evt);
            }
        });
        jPanel2.add(isrValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 90, -1));

        jLabel13.setText("Isr");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, -1, -1));

        jTabbedPane1.addTab("Editar", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Filtrar Por:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, -1));

        jLabel16.setText("Nombre:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        jPanel3.add(nombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 130, -1));

        jLabel17.setText("Nit:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));
        jPanel3.add(nitFiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 130, -1));

        jLabel18.setText("Cui");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 30, -1));
        jPanel3.add(cuiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 130, -1));

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, -1));

        jTabbedPane1.addTab("Buscar", jPanel3);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 230, 790, 210);

        jButton4.setText("Reestablecer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(860, 360, 120, 32);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        menu mn = new menu();
        if(privilegiosAdmin){
            menu.gestionUsuarios.setEnabled(true);
        }else{
            menu.gestionUsuarios.setEnabled(false);
        }
        menu.etiquetaRol.setText(textoRol);
        menu.etiquetaUsuario.setText(textoUsuario);
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        if (!idTexto.getText().toString().equals("")) {

            ClienteService clienteSer = new ClienteService();
            Cliente cliente = clienteSer.encontrarPorId(new Cliente(Integer.parseInt(idTexto.getText())));
            cliente.setNombre(NombreTexto.getText());
            cliente.setApellido(ApellidoTexto.getText());
            cliente.setCui(Integer.parseInt(cuiTexto.getText()));
            cliente.setEdad(Integer.parseInt(edadTexto.getText()));
            cliente.getIdContacto().setTelefono1(telefono1Texto.getText());
            cliente.getIdContacto().setTelefono2(telefono2Texto.getText());
            cliente.getIdDireccion().setDireccion(direcctionTexto.getText());
            cliente.setNit(nitTexto.getText());
            cliente.getIdContacto().setEmail(emailTexto.getText());
            cliente.getIdEmpresa().setNombreEmpresa(empresaTexto.getText());

            if (isrValores.getSelectedItem().toString().equals("mensual")) {
                cliente.setIdIsr(new Isr("mensual"));
            } else if (isrValores.getSelectedItem().toString().equals("trimestral")) {
                cliente.setIdIsr(new Isr("trimestral"));
            }
            if(contribuyenteValores.getSelectedItem().toString().equals("normal")){
                cliente.setIdContribuyente(new Contribuyente("normal"));
            }else if(contribuyenteValores.getSelectedItem().toString().equals("pequeño")){
                cliente.setIdContribuyente(new Contribuyente("pequeño"));
            }
            
            clienteSer.modificarCliente(cliente);
            this.idTexto.setText("");
            this.NombreTexto.setText("");
            this.ApellidoTexto.setText("");
            this.cuiTexto.setText("");
            this.edadTexto.setText("");
            this.telefono1Texto.setText("");
            this.telefono2Texto.setText("");
            this.direcctionTexto.setText("");
            this.nitTexto.setText("");
            this.emailTexto.setText("");

            this.empresaTexto.setText("");
            ClienteService servicio = new ClienteService();
            isrValores.removeAllItems();
            this.isrValores.addItem("--------");
            contribuyenteValores.removeAllItems();
            contribuyenteValores.addItem("--------");

            DefaultTableModel nuevo = new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "ID Cliente", "Nombre", "Apellido", "CUI", "Edad", "Telefono 1", "Telefono 2", "Direccion", "NIT", "Email", "Contribuyente", "ISR", "Empresa"
                    }
            ) {
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false, false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            
            List<Cliente> clientes = servicio.listarClientes();
            for (Cliente c : clientes) {
                nuevo.addRow(new Object[]{c.getIdCliente().toString(), c.getNombre(), c.getApellido(),
                    c.getCui().toString(), c.getEdad(), c.getIdContacto().getTelefono1(),
                    c.getIdContacto().getTelefono2(), c.getIdDireccion().getDireccion(),
                    c.getNit(), c.getIdContacto().getEmail(), c.getIdContribuyente().getDescripcion(),
                    c.getIdIsr().getTipoIsr(), c.getIdEmpresa().getNombreEmpresa()});
            }
            jTable1.setModel(nuevo);
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona Un Renglon", "Error", JOptionPane.ERROR_MESSAGE);
            this.idTexto.setText("");
            this.NombreTexto.setText("");
            this.ApellidoTexto.setText("");
            this.cuiTexto.setText("");
            this.edadTexto.setText("");
            this.telefono1Texto.setText("");
            this.telefono2Texto.setText("");
            this.direcctionTexto.setText("");
            this.nitTexto.setText("");
            this.emailTexto.setText("");

            this.empresaTexto.setText("");
            isrValores.removeAllItems();
            this.isrValores.addItem("--------");
            contribuyenteValores.removeAllItems();
            contribuyenteValores.addItem("--------");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        
        this.idTexto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        this.NombreTexto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        this.ApellidoTexto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        this.cuiTexto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        this.edadTexto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        this.telefono1Texto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
        this.telefono2Texto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
        this.direcctionTexto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
        this.nitTexto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
        this.emailTexto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
        this.empresaTexto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 12).toString());
        isrValores.removeAllItems();
        this.isrValores.addItem("mensual");
        this.isrValores.addItem("trimestral");
        contribuyenteValores.removeAllItems();
        contribuyenteValores.addItem("normal");
        contribuyenteValores.addItem("pequeño");
    }//GEN-LAST:event_jTable1MouseClicked

    private void isrValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isrValoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isrValoresActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        ClienteService servicio = new ClienteService();

        if (!this.cuiField.getText().equals("")) {
            DefaultTableModel nuevo = (DefaultTableModel) jTable1.getModel();
            
            TableRowSorter<TableModel> modeloFiltrado = new TableRowSorter<TableModel>(nuevo);
            jTable1.setRowSorter(modeloFiltrado);
            modeloFiltrado.setRowFilter(RowFilter.regexFilter(cuiField.getText(), 3));
            
        } else if (!this.nitFiled.getText().equals("")) {

            DefaultTableModel nuevo = new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "ID Cliente", "Nombre", "Apellido", "CUI", "Edad", "Telefono 1", "Telefono 2", "Direccion", "NIT", "Email", "Contribuyente", "ISR", "Empresa"
                    }
            ) {
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false, false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            jTable1.setModel(nuevo);
            List<Cliente> clientes = servicio.listarClientes();
            for (Cliente c : clientes) {
                nuevo.addRow(new Object[]{c.getIdCliente().toString(), c.getNombre(), c.getApellido(),
                    c.getCui().toString(), c.getEdad(), c.getIdContacto().getTelefono1(),
                    c.getIdContacto().getTelefono2(), c.getIdDireccion().getDireccion(),
                    c.getNit(), c.getIdContacto().getEmail(), c.getIdContribuyente().getDescripcion(),
                    c.getIdIsr().getTipoIsr(), c.getIdEmpresa().getNombreEmpresa()});
            }
            TableRowSorter<TableModel> modeloFiltrado = new TableRowSorter<TableModel>(nuevo);
            jTable1.setRowSorter(modeloFiltrado);
            modeloFiltrado.setRowFilter(RowFilter.regexFilter(nitFiled.getText(), 8));
            modeloFiltrado = null;
        } else if (!this.nombreField.getText().equals("")) {
            DefaultTableModel nuevo = new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "ID Cliente", "Nombre", "Apellido", "CUI", "Edad", "Telefono 1", "Telefono 2", "Direccion", "NIT", "Email", "Contribuyente", "ISR", "Empresa"
                    }
            ) {
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false, false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }

            };
            jTable1.setModel(nuevo);
            List<Cliente> clientes = servicio.listarClientes();
            for (Cliente c : clientes) {
                nuevo.addRow(new Object[]{c.getIdCliente().toString(), c.getNombre(), c.getApellido(),
                    c.getCui().toString(), c.getEdad(), c.getIdContacto().getTelefono1(),
                    c.getIdContacto().getTelefono2(), c.getIdDireccion().getDireccion(),
                    c.getNit(), c.getIdContacto().getEmail(), c.getIdContribuyente().getDescripcion(),
                    c.getIdIsr().getTipoIsr(), c.getIdEmpresa().getNombreEmpresa()});
            }

            TableRowSorter<TableModel> modeloFiltrado = new TableRowSorter<TableModel>(nuevo);
            jTable1.setRowSorter(modeloFiltrado);
            modeloFiltrado.setRowFilter(RowFilter.regexFilter("(?i)"+nombreField.getText(), 1));
            modeloFiltrado = null;
        } else {
            JOptionPane.showMessageDialog(null, "Introduce Datos Para Buscar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        ClienteService servicio = new ClienteService();
        DefaultTableModel nuevo = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID Cliente", "Nombre", "Apellido", "CUI", "Edad", "Telefono 1", "Telefono 2", "Direccion", "NIT", "Email", "Contribuyente", "ISR", "Empresa"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        List<Cliente> clientes = servicio.listarClientes();
        for (Cliente c : clientes) {
            nuevo.addRow(new Object[]{c.getIdCliente().toString(), c.getNombre(), c.getApellido(),
                c.getCui().toString(), c.getEdad(), c.getIdContacto().getTelefono1(),
                c.getIdContacto().getTelefono2(), c.getIdDireccion().getDireccion(),
                c.getNit(), c.getIdContacto().getEmail(), c.getIdContribuyente().getDescripcion(),
                c.getIdIsr().getTipoIsr(), c.getIdEmpresa().getNombreEmpresa()});
        }
        jTable1.setModel(nuevo);
        jTable1.setRowSorter(new TableRowSorter(nuevo));
        jTable1.setAutoCreateRowSorter(true);
        cuiField.setText("");
        nombreField.setText("");
        nitFiled.setText("");
        
        idTexto.setText("");
        NombreTexto.setText("");
        ApellidoTexto.setText("");
        cuiTexto.setText("");
        edadTexto.setText("");
        telefono1Texto.setText("");
        telefono2Texto.setText("");
        direcctionTexto.setText("");
        nitTexto.setText("");
        emailTexto.setText("");
        empresaTexto.setText("");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void NotMain(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoTexto;
    private javax.swing.JTextField NombreTexto;
    private javax.swing.JComboBox<String> contribuyenteValores;
    private javax.swing.JTextField cuiField;
    private javax.swing.JTextField cuiTexto;
    private javax.swing.JTextField direcctionTexto;
    private javax.swing.JTextField edadTexto;
    private javax.swing.JTextField emailTexto;
    private javax.swing.JTextField empresaTexto;
    private javax.swing.JTextField idTexto;
    private javax.swing.JComboBox<String> isrValores;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JTextField nitFiled;
    private javax.swing.JTextField nitTexto;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField telefono1Texto;
    private javax.swing.JTextField telefono2Texto;
    // End of variables declaration//GEN-END:variables
    public static boolean privilegiosAdmin = false;
    public static String textoUsuario = "";
    public static String textoRol = "";
}
